server {
    listen 80;
    server_name _;
    root /data;

    location / {
        autoindex off;
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
        add_header Access-Control-Allow-Origin *;
    }

    gzip on;
    gzip_types image/svg+xml text/plain application/json;
}
